### ISSUE TITLE
Can't resolve underscore

### ISSUE THREAD

**Issue by brandonkal** [silvermine/videojs-airplay#11]
https://github.com/silvermine/videojs-airplay/blob/c1b783ab4f0a7f13a340c9f83469a7b05b73d56a/src/js/enableAirPlay.js#L8

You are requiring underscore but it is not listed as a dependency in your package.json. Is this plugin still maintained? Thanks.

**Comment by jthomerson** [comment]
😕 @yokuze ? Not sure how we missed that. I guess because everywhere we're using it, `_` is available.
