### ISSUE TITLE
Airplay is not working in some browsers - videojs-7.6.6

### ISSUE THREAD

**Issue by heltonalves99** [silvermine/videojs-airplay#20]
Hi guys, how are you ?

we are using the last version of videojs, 7.6.6 version.

is videojs-airplay working fine with that version ?
because we tried in some browsers, and it doesn't work in all!
ex: we tried in Safari, the button showed up, but when we click on it, nothing happens.

**Comment by jthomerson** [comment]
@heltonalves99 as far as we know, this plugin is compatible with versions 6 and 7 of VideoJS. That said, don't have time to test each and every version of VideoJS with our plugins. If you'd like assistance, you will need to post a [minimal, complete, verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) (MCVE). Sometimes just by creating a MCVE you will actually discover the source of the problem yourself - or at least more details to help us reproduce it.

If you want some good examples of MCVE's, see a couple of issues that we have posted elsewhere, e.g:

 * https://github.com/videojs/video.js/issues/4765
 * https://github.com/videojs/http-streaming/issues/172

All of that detail is really important in getting help - especially on an open source plugin where people are donating their time. Without it we can't be sure what version of VideoJS you're using, or what other plugins you're using with it.

If you're able to reproduce the issue in an MCVE, post a comment here and the issue can be reopened.
