### ISSUE TITLE
webkitplaybacktargetavailabilitychanged listener is not removed when AirPlayButton is disposed

### ISSUE THREAD

**Issue by ddunkin** [silvermine/videojs-airplay#29]
The event listener is not removed when the AirPlayButton is disposed, so if the event is raised, AirPlayButton tries to hide or show itself, but `this._el` is null and an error is throw.

**Comment by kontrollanten** [comment]
We've issues with this as well. @izkmdz Can you create a pull request with your fix?

**Comment by yokuze** [comment]
> We've issues with this as well. @izkmdz Can you create a pull request with your fix?

https://github.com/silvermine/videojs-airplay/pull/35 Should have taken care of it @kontrollanten. We are actively working in this repo over the next month or so, so won't publish a new version just yet. For now, you could NPM install using a `git+ssh` / `git+https` url with the latest `master` hash, if you'd like.

**Comment by kontrollanten** [comment]
Oh, great. Thanks!
