### ISSUE TITLE
videojs.extend has been removed from VideoJS v8

### ISSUE THREAD

**Issue by denizb** [silvermine/videojs-airplay#45]
Will there be an update to move toward E6 classes to replace the videojs.extend method?

**Comment by mdijkstra-oss** [comment]
Also running into this issue.

<img width="973" alt="Screenshot 2023-03-26 at 16 21 09" src="https://user-images.githubusercontent.com/1755544/227782118-e6b090ef-2b76-488d-a6b2-44bc7c15df75.png">

**Comment by kevireilly** [comment]
#44 appears to be addressing this incompatibility

**Comment by marcellov7** [comment]
news?

**Comment by damanV5** [comment]
@kevireilly  Any update?

**Comment by kevireilly** [comment]
Unfortunately it seems like the pull request is still pending. Curious if others were looking to add Chromecast in addition to AirPlay?

**Comment by kevireilly** [comment]
Edited `npm install https://github.com/kevireilly/videojs-casting` which doesn't work to `npm install kevireilly/videojs-casting` which should.

**Comment by kevireilly** [comment]
When trying the installation suggestion above today in a separate project, had a bit of problems preventing that from "just working". For now, it is probably easiest to just copy/paste the plugin.js and plugin.css to your project then import and instantiate the plugin like you would other plugins.

**Comment by yokuze** [comment]
#44 Was just merged. We will release a new version soon. Thanks @denizb / @kevireilly / @damanV5  / @marcellov7 / @matthijn.

**Comment by damanV5** [comment]
Thankyou! @yokuze .

**Comment by marcellov7** [comment]
> new version soon

Hi, 
I still can't see the new version.
thanks

**Comment by cjrondini2** [comment]
RIP?

**Comment by yokuze** [comment]
v1.3.0 was released last week, which includes the removal of any use of `.extend`. Give it a try.
