### ISSUE TITLE
How to solve the warn log?

### ISSUE THREAD

**Issue by Untrula** [silvermine/videojs-airplay#49]
Users of the library are seeing this warning in the browser console:
`VIDEOJS: WARN: videojs.extend is deprecated as of Video.js 7.22.0 and will be removed in Video.js 8.0.0`

How to solve the warn log? Thx~

**Comment by kevireilly** [comment]
#44

**Comment by yokuze** [comment]
This is addressed with v1.3.0 of this plugin. Thanks
