### ISSUE TITLE
More frequent releases | Create a new tag

### ISSUE THREAD

**Issue by ToshY** [silvermine/videojs-airplay#50]
@jthomerson  @yokuze @izkmdz 

I'd like to see more frequent releases. Majority of the time PRs get merged but no new tags are created. As a user I occasionally mention maintainers in issues/PRs in the hope they see it, but lots of times it takes months before even gets noticed or delegated to the right person, and even longer before it gets merged.

With new fixes/changes in the current `master` branch, it would be very much appreciated if a maintainer could create a new tag.

> **Note**
> The same goes for [silvermine/videojs-chromecast](https://github.com/silvermine/videojs-chromecast)

**Comment by ToshY** [comment]
@jthomerson @yokuze @izkmdz ping

**Comment by yokuze** [comment]
v1.3.0 was released last week.

**Comment by ToshY** [comment]
@yokuze Thanks for notifying!
